apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-exporter
  template:
    metadata:
      labels:
        app: mosquitto-exporter
    spec:
      containers:
      - name: mosquitto-exporter
        image: sapcc/mosquitto-exporter
        env:
        - name: BROKER_ENDPOINT
          value: "mosquitto-service.t3testing.svc:1883"  # Replace <your-project> with your actual project name
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-exporter-service
spec:
  selector:
    app: mosquitto-exporter
  ports:
    - protocol: TCP
      port: 9234
      targetPort: 9234
